language: node_js
node_js:
  - '8'
  - '6'
  - '4'
services:
  - redis-server
  - mongodb
  - postgresql
before_script:
  - psql -c 'create database keyv_test;' -U postgres
script: npm run test:full
after_success: npm run coverage
notifications:
  email:
    on_success: never
